Args = --no-fallback \
       --report-unsupported-elements-at-runtime \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=org.slf4j \
       --initialize-at-run-time=com.sun.javafx.application.PlatformImpl,org.controlsfx,com.sun.glass.ui.Application,com.sun.glass.ui.gtk.GtkApplication,com.sun.glass.ui.mac.MacApplication
