Args = --no-fallback \
       --report-unsupported-elements-at-runtime \
       -H:+ReportExceptionStackTraces \
       --initialize-at-run-time=com.sun.javafx.application.PlatformImpl,org.controlsfx
